name: Find next person on call
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Developer Weekday Schedule
        id: dev-weekday
        uses: mxie/pagerduty-oncall-action@main
        with:
          token: ${{ secrets.PAGERDUTY_TOKEN }}
          schedule-id: PPQBFP9

      - name: Critical Issues Schedule
        if: always()
        id: critical-issue
        uses: mxie/pagerduty-oncall-action@main
        with:
          token: ${{ secrets.PAGERDUTY_TOKEN }}
          schedule-id: PYJ6MPP

      - name: Critical Escalation Schedule
        if: always()
        id: escalation
        uses: mxie/pagerduty-oncall-action@main
        with:
          token: ${{ secrets.PAGERDUTY_TOKEN }}
          schedule-id: P2SAWCS

      - name: Dev Weekday
        if: always()
        run: echo ${{ steps.dev-weekday.outputs.person }} is on call

      - name: Critical Issues
        if: always()
        run: echo ${{ steps.critical-issue.outputs.person }} is on call

      - name: Escalation
        if: always()
        run: echo ${{ steps.escalation.outputs.person }} is on call


      # Piotr Kosinski until 8:30 AM Monday, June 27th